feat: add export and import knowledge on BDC
LINCnil/pia pull request #573
Opened 2021-08-31 09:54 UTC by Timothee-Picard

2021-08-31 12:25 UTC, brunto requested changes

2021-08-31 12:25 UTC, brunto commented on src/app/services/knowledge-base.service.ts
> +        console.log(data);
Please remove the console.log()

2021-08-31 13:56 UTC, syl-p submitted a review, later dismissed

2021-08-31 14:10 UTC, syl-p approved these changes

2021-08-31 14:11 UTC, syl-p approved these changes

2021-09-01 07:18 UTC, brunto approved these changes

2021-09-01 07:18 UTC, merged