Patch vulnérabilité
LINCnil/pia pull request #790
Opened 2024-12-17 11:29 UTC by alphaleadership

2024-12-17 14:06 UTC, alphaleadership commented
@brunto

2025-01-06 08:07 UTC, brunto commented
Thank you for your contribution. We will look into it soon.
Could you also run `yarn install` to update the yarn.lock?

2025-01-06 11:09 UTC, alphaleadership commented
Yes

2025-01-06 12:27 UTC, kevin-atnos requested changes

2025-01-06 12:27 UTC, kevin-atnos commented on package.json
> +    "@angular-devkit/build-angular": "^19.0.0",
Hello @alphaleadership , thank you for your contribution.
You can't upgrade to a higher version of Angular like this. Please do not upgrade to a major version. Only the security version is allowed for now.

2025-01-06 14:41 UTC, alphaleadership commented on package.json
> +    "@angular-devkit/build-angular": "^19.0.0",
Is only security update

2025-03-11 16:11 UTC, closed without merging